# Generated by Django 4.2 on 2023-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_group'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='pets',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
