# Generated by Django 4.2 on 2023-04-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0004_rename_name_trait_trait_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
