# Generated by Django 4.2 on 2023-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_alter_trait_trait_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='trait_name',
        ),
        migrations.AddField(
            model_name='trait',
            name='name',
            field=models.CharField(default='name', max_length=20, unique=True),
        ),
    ]
