# Generated by Django 4.2 on 2023-04-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0010_alter_trait_hehe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='hehe',
            field=models.CharField(db_column='hihi', default='heihe', max_length=20, unique=True),
        ),
    ]
