# Generated by Django 4.2 on 2023-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0011_alter_trait_hehe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='hehe',
        ),
        migrations.AddField(
            model_name='trait',
            name='name',
            field=models.CharField(db_column='name', default='name', max_length=20, unique=True),
        ),
    ]
