# Generated by Django 4.2 on 2023-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0014_trait_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='nome',
        ),
        migrations.AddField(
            model_name='trait',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
