# Generated by Django 4.2 on 2023-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0015_remove_trait_nome_trait_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(default='change', max_length=20),
        ),
    ]
