# Generated by Django 4.2 on 2023-04-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0016_alter_trait_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='name',
            new_name='me',
        ),
    ]
