# Generated by Django 4.2 on 2023-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0017_rename_name_trait_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='me',
        ),
        migrations.AddField(
            model_name='trait',
            name='name',
            field=models.CharField(default='name', max_length=20, unique=True),
        ),
    ]
